### ISSUE TITLE
2 qubit environment is sometimes very slow

### ISSUE THREAD

**Issue by Farquhar13** [akataba/rl-repo#12]
It seems that some scripts run in a reasonable amount of time, but sometimes the speed of moving through steps is very slow. 

Try to understand what part of the code the slow down is coming from.

**Comment by Farquhar13** [comment]
I know we talked about this a while ago; is this still an issue @choihrM3?

**Comment by choihrM3** [comment]
Slowdown is still true when the number of steps goes very large (n_iterations > 50).
However, the execution is okay-level and slowdown is tens of percentage level.
