### ISSUE TITLE
gamma --> alpha variable name

### ISSUE THREAD

**Issue by Farquhar13** [akataba/rl-repo#21]
https://github.com/akataba/rl-repo/blob/c51a62b2ca182ee2d0050db0352d9be37ed90271/src/relaqs/environments/gate_synth_env_rllib_Haar.py#L82

Should this be `self.alpha_detuning_max` instead of `self.gamma_detuning_max`? @choihrM3

**Comment by choihrM3** [comment]
Yes, alpha seems more natural. I think it's my mistake.
