### ISSUE TITLE
Haar Basis Defaults

### ISSUE THREAD

**Issue by Farquhar13** [akataba/rl-repo#22]
https://github.com/akataba/rl-repo/blob/c51a62b2ca182ee2d0050db0352d9be37ed90271/src/relaqs/environments/gate_synth_env_rllib_Haar.py#L452C1-L453C39

Hey @choihrM3 did these default values change? Are they correct?

**Comment by choihrM3** [comment]
In more recent version, this is changed to,

self.current_Haar_num = 2
self.current_step_per_Haar = 1

For the two-qubit one, self.current_Haar_num should be at least 2. Any default values should be fine, but perhaps starting with (2,1) is safe?
