### ISSUE TITLE
Fix bug in save_env_transitions

### ISSUE THREAD

**Issue by Farquhar13** [akataba/rl-repo#25]
Issue with saving in the numpy format. 

I believe the issue can be solved by unpacking the lists in `self.env_transitions` of the environment classes.

```
  File "/Users/collinfarquhar/Code/rl-repo/src/relaqs/save_results.py", line 98, in save_env_transitions
    np.save(f, np.array(self.env.transition_history))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2002, 5) + inhomogeneous part.
```

**Comment by Farquhar13** [comment]
The change where the list unpacking was lost was introduced in this [PR](https://github.com/akataba/rl-repo/commit/465c440a1705bc6c3227bf486e001239b1f74206#diff-6dcede3d39983ab80b83776a2eeb501a241fa1ecfdbac31ec92e438e3d9bb07d) 

@akataba, is the format you've introduced here for the `self.env_transitions` object relied on by any analysis code or can we change it back?

**Comment by akataba** [comment]
@Farquhar13  This allowed me to format the saved CSV file in such a way that  for a pandas frame each column in the CSV file can correspond to a column in the pandas dataframe and each row easily correspond to an episode. I forget the details but the essence is that the pandas dataframes would be easier to use.

**Comment by Farquhar13** [comment]
@akataba thanks! I think using a pandas dataframe is a good idea. I'll work on switching over to that.
