### ISSUE TITLE
Reward function discrepancy between 1 and 2 qubit environments

### ISSUE THREAD

**Issue by Farquhar13** [akataba/rl-repo#36]
Are the different coefficients in the reward functions intended @choihrM3?

One qubit reward:
`(-3 * np.log10(1.0 - fidelity) + np.log10(1.0 - self.prev_fidelity)) + (3 * fidelity - self.prev_fidelity)`

Two qubit reward:
`(-5 * np.log10(1.0 - fidelity) + np.log10(1.0 - self.prev_fidelity)) + (5 * fidelity - self.prev_fidelity)`

**Comment by choihrM3** [comment]
Not much. I will use the later version for the two-qubit ones for the consistency.

**Comment by choihrM3** [comment]
I put 1.0000001 instead of 1.0, just in case that we are hitting 1.0 exactly and error.

reward = (-3 * np.log10(1.0000001 - fidelity) + np.log10(1.0000001 - self.prev_fidelity)) + (3 * fidelity - self.prev_fidelity)
